// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ffiblecommunicator.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Bootstrapper>>
abstract class Bootstrapper implements RustOpaqueInterface {
  Future<void> bootstrap({required String serialNumber});

  static Future<Bootstrapper> init(
          {required ParsedConfig config,
          required FfibleCommunicator communicator}) =>
      RustLib.instance.api.crateApiBootstrapperBootstrapperInit(
          config: config, communicator: communicator);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ParsedConfig>>
abstract class ParsedConfig implements RustOpaqueInterface {}
