// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'bootstrapper.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ParsedConfig> getConfig(
        {required String eeCert,
        required String eeKey,
        required String registrarCert}) =>
    RustLib.instance.api.crateApiConfigGetConfig(
        eeCert: eeCert, eeKey: eeKey, registrarCert: registrarCert);
